export default [
    {
        id: "1",
        name: "Nature Sentinel",
        type: "Game",
        img: "game/nature-sentinel.png",
        description: "A turn & grid based strategy game made on my own time, featuring art, animations, and coding all done by me. This was my first time working with complex algorithms, especially the A* pathfinding algorithm.",
        url: "https://groober.itch.io/nature-sentinel",
    },
    {
        id: "2",
        name: "Opportunities",
        type: "Art",
        img: "art/opportunities.png",
        description: "A small project I did for the purpose of studying the anatomy of hands, this piece is to convey the wonders of life through oppourtunity represented by all the hands. I learned a lot from this one.",
        url: "https://i.imgur.com/Y4HVDpa.jpg",
    },
    {
        id: "3",
        name: "Anger Management",
        type: "Game",
        img: "game/anger-management.png",
        description: "A simulator physics game that was made for the YRHacks 2022 hackathon, done in less than 24 hours with a group. Working on this one was very tough, it required a lot of good communication and planning.",
        url: "https://groober.itch.io/anger-management",
    },
    {
        id: "4",
        name: "Tetris Players Toronto Cards",
        type: "Website",
        img: "website/tpt-cards.png",
        description: "A website made to show off stats of modern Tetris players who play TETR.IO, information is fetched directly from the TETR.IO API. This website was originally intended to be a little bit of react practice.",
        url: "https://github.com/groobob/TPT-PlayerCards",
    },
    {
        id: "5",
        name: "Picnic",
        type: "Art",
        img: "art/picnic.png",
        description: "A study based off of a real photo done to really practice and improve my own art skills, I am pretty happy with how this one turned out! But of course, there is much to improve.",
        url: "https://i.imgur.com/BXiejKb.png",
    },
    {
        id: "6",
        name: "Personal Portfolio",
        type: "Website",
        img: "website/personal-portfolio.png",
        description: "The website you're on right now! This website is by far my largest acomplishment when it comes to React and web development, hope you like it here!",
        url: "https://github.com/groobob/Portfolio-Website",
    },
    
]